name: moldesign-demo
channels:
  - defaults
  - conda-forge
dependencies:
# Core dependencies
  - python==3.14.*
  - pip

# Dependencies from the molecular design app
  - rdkit
  - xtb-python

# Pip install Parsl and the local functions
  - pip:
      - -e .
