name: tests

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  unit:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python: '3.10'
          toxenv: py310
        - os: ubuntu-latest
          python: '3.11'
          toxenv: py311
        - os: ubuntu-latest
          python: '3.12'
          toxenv: py312
        - os: ubuntu-latest
          python: '3.13'
          toxenv: py313
        - os: ubuntu-latest
          python: '3.14'
          toxenv: py314
        - os: macos-latest
          python: '3.10'
          toxenv: py310
        - os: macos-latest
          python: '3.11'
          toxenv: py311
        - os: macos-latest
          python: '3.12'
          toxenv: py312
        - os: macos-latest
          python: '3.13'
          toxenv: py313
        - os: macos-latest
          python: '3.14'
          toxenv: py314
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Get pip cache dir
        id: pip-cache-dir
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Use pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: tests-unit-${{ matrix.os }}-pip-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tests-unit-${{ matrix.os }}-pip-${{ matrix.python }}-

      - name: Install Packages
        run: python -mpip install --upgrade pip tox

      # Patch misconfigured /etc/hosts config on some MacOS runners
      # See https://github.com/academy-agents/academy/pull/220
      - name: Patch /etc/hosts on MacOS
        if: runner.os == 'macos-latest'
        run: echo 127.0.0.1 $(python3 -c 'import platform; print(platform.node())') | sudo tee -a /etc/hosts

      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }} -- -vv

  integration:
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python: '3.10'
          toxenv: py310-integration
        - os: ubuntu-latest
          python: '3.11'
          toxenv: py311-integration
        - os: ubuntu-latest
          python: '3.12'
          toxenv: py312-integration
        - os: ubuntu-latest
          python: '3.13'
          toxenv: py313-integration
        - os: ubuntu-latest
          python: '3.14'
          toxenv: py314-integration
        - os: macos-latest
          python: '3.10'
          toxenv: py310-integration
        - os: macos-latest
          python: '3.11'
          toxenv: py311-integration
        - os: macos-latest
          python: '3.12'
          toxenv: py312-integration
        - os: macos-latest
          python: '3.13'
          toxenv: py313-integration
        - os: macos-latest
          python: '3.14'
          toxenv: py314-integration
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Get pip cache dir
        id: pip-cache-dir
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Use pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: tests-integration-${{ matrix.os }}-pip-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tests-integration-${{ matrix.os }}-pip-${{ matrix.python }}-

      - name: Install Packages
        run: python -mpip install --upgrade pip tox

      # Patch misconfigured /etc/hosts config on some MacOS runners
      # See https://github.com/academy-agents/academy/pull/220
      - name: Patch /etc/hosts on MacOS
        if: runner.os == 'macos-latest'
        run: echo 127.0.0.1 $(python3 -c 'import platform; print(platform.node())') | sudo tee -a /etc/hosts

      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }} -- -vv
